#
# Automatically determine the version from the last git tag.
#
{% if GIT_DESCRIBE_NUMBER|int == 0 %}
  {% set version = GIT_DESCRIBE_TAG %}
{% else %}
  # If we're using a non-tagged revision, append '.postN' to the version
  {% set version = GIT_DESCRIBE_TAG + '.post' + GIT_DESCRIBE_NUMBER %}
{% endif %}

package:
  name: vol2mesh
  version: "{{ version }}"

source:
  path: ..

build:
  number: 0
  string: "{{ PKG_BUILDNUM }}_py{{ CONDA_PY }}_g{{ GIT_FULL_HASH[:7] }}"
  noarch: python

outputs:
  # The base package has fewer dependencies,
  # but lacks some functionality:
  #  - the scikit-image marching cubes implementation
  #  - numba acceleration for normals calculation
  #  - laplacian smoothing on an existing mesh
  #  - stitching multiple meshes together into a water-tight whole
  - name: vol2mesh-base
    script: build_base.sh
    build:
      noarch: python
    requirements:
      build:
        - python >=3.6
        - pip
        - setuptools
      run:
        - python >=3.6
        - numpy >=1.22.4
        - pandas
        - scipy
        - lz4 >=2

        # See README for details about these dependencies
        - marching_cubes >=0.2
        - fq-mesh-simplification
        - dvidutils >=0.0.post81

    test:
      imports:
        - vol2mesh

  - name: vol2mesh
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage('vol2mesh-base', exact=True) }}
        - scikit-image >=0.13
        - numba
        - openmesh-python

    test:
      imports:
        - vol2mesh
      requires:
        - pytest
      commands:
        - pytest -s --tb=native --pyargs vol2mesh.tests

about:
  home: https://github.com/janelia-flyem/vol2mesh
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Tools for converting image volumes to meshes
